keycloak:
  server-url: http://localhost:7080
  realm: task-flow
  client-id: user-service
  client-secret: 79dyMume8VhISaRQeyEizfoJ8R7S9vI7
eureka:
  server-url: http://localhost:8761
admin:
  server-url: http://localhost:8085
kafka:
  bootstrap-servers: localhost:9092