keycloak:
  server-url: http://localhost:7080
  realm: task-flow
  admin-client-id: admin-service
  admin-client-secret: TiCxUfEoRaVneYChHgEB1HXmykZxin0R
  client-id: user-service
eureka:
  server-url: http://localhost:8761