server:
  port: 8080
spring:
  application:
    name: user-service
  thymeleaf:
    enabled: false
  boot:
    admin:
      client:
        url: ${admin.server-url}
        instance:
          name: user-service
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username
        registration:
          discovery:
            provider: keycloak
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: client_credentials
            scope:
              - discovery
          metrics:
            provider: keycloak
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: client_credentials
            scope:
              - metrics
jwt:
  auth:
    converter:
      resource-id: ${keycloak.client-id}
eureka:
  client:
    service-url:
      defaultZone: ${eureka.server-url}/eureka/
  instance:
    prefer-ip-address: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'