keycloak:
  server-url: http://localhost:7080
  realm: task-flow
  client-id: analytics-service
  client-secret: bkNriWXAEWq6o8OvLNK3fQ6SDquo1aj7
eureka:
  server-url: http://localhost:8761
task:
  server-url: lb://task-service
  registration-id: keycloak
redis:
  host: localhost
  port: 6379