server:
  port: 8085
spring:
  application:
    name: admin-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
        registration:
          keycloak:
            client-id: ${keycloak.admin-client-id}
            client-secret: ${keycloak.admin-client-secret}
            authorization-grant-type: client_credentials
            scope:
              - metrics
          discovery:
            provider: keycloak
            client-id: ${keycloak.admin-client-id}
            client-secret: ${keycloak.admin-client-secret}
            authorization-grant-type: client_credentials
            scope:
              - discovery
jwt:
  auth:
    converter:
      resource-id: ${keycloak.client-id}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    service-url:
      defaultZone: ${eureka.server-url}/eureka/
  instance:
    prefer-ip-address: true