server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/r1zhok/task-flow-config
          clone-on-start: true
  security:
    user:
      name: admin
      password: admin